name: quality-gateway
run-name: Quality Gateway
on: 
  pull_request:
    branches:
      - main
      - staging
jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn test