name: vercel-stg-deployment
run-name: Vercel staging deployment
on:
  push:
    branches: ['staging']
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn deploy