name: vercel-prod-deployment
run-name: Vercel production deployment
on:
  push:
    branches: ['main']
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      - run: chmod +x ./scripts/vercel-deployment.sh && ./scripts/vercel-deployment.sh